CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE DATABASE IF NOT EXISTS testdb;
CREATE USER 'zenusr'@'localhost' IDENTIFIED BY 'userP@ss2024';
GRANT ALL PRIVILEGES ON `testdb`.* TO 'zenusr'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

